- job:
    name: python-barbicanclient-tox-functional
    parent: devstack-tox-functional
    timeout: 4200
    required-projects:
      - openstack/barbican
      - openstack/barbican-tempest-plugin
      - openstack/python-barbicanclient
    vars:
      devstack_plugins:
        barbican: https://opendev.org/openstack/barbican

- project:
    templates:
      - check-requirements
      - openstack-python3-wallaby-jobs
      - openstackclient-plugin-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - python-barbicanclient-tox-functional
    gate:
      jobs:
        - python-barbicanclient-tox-functional
